name: code

on:
  push:
    branches: master
  pull_request:
    branches: master
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: build 
        run: |
          git submodule update --init --recursive
          cmake -B _build
          cd _build
          make
          cd ..
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: testing
        run: |
          git submodule update --init --recursive
          cmake -B _build
          cd _build
          make
          ./check
          cd ..
      - name: lcov_install
        run: |
          sudo apt-get install -y lcov
      - name: lcov
        run: |
          lcov --capture --directory _build/CMakeFiles/banking.dir/banking -o ./lcov.info
      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
            path-to-lcov: "./lcov.info"
            github-token: ${{ secrets.github_token }}
